name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        ruby-version: [2.7.4, 3.0.2]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.6

      - name: Install dependencies
        run: |
          sudo apt-get install -y build-essential
          export RAILS_ENV=test
          gem install bundler
          make setup

      - name: Run ci
        run: make ci
